CREATE STREAM s_orders (id VARCHAR KEY, state VARCHAR, cust_email VARCHAR) WITH (KAFKA_TOPIC = 'orders', VALUE_FORMAT = 'JSON');
CREATE TABLE t_orders AS SELECT ID AS O_ID, LATEST_BY_OFFSET(STATE) AS O_STATE FROM s_orders GROUP BY ID;
SHOW TOPICS;
SHOW STREAMS;
SHOW TABLES;
SHOW PROPERTIES;

